# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  # Azure service connection established during pipeline creation
  azureSubscription: AzureRmPipeline-conn
  appName: avvaruprojWebApp
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

steps:
# Restore multiple projects
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: |
      pipelines-dotnet-core.csproj
# Build multiple projects
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: |
      pipelines-dotnet-core.csproj
# Pack a NuGet package to a test directory
- task: DotNetCoreCLI@2
  inputs: 
    command: 'pack'
    outputDir: '$(Build.ArtifactStagingDirectory)'
# Publish build artifacts to Azure Pipelines or a Windows file share
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: MyBuildOutputs
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: $(azureSubscription)
    subscriptionId: '9ff09445-7de7-4852-b924-6f22be074670'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'avvarurg'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName avvaruproj -linkedTemplateUri https://raw.githubusercontent.com/anil-kumar-appliedis/pipelines-dotnet-core/master/CreateWebApp/linkedStorageAccount.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
- task: AzureWebApp@1 # Add this at the end of your file
  inputs:
    azureSubscription: $(azureSubscription)
    appType: webAppLinux
    appName: $(appName)
    package: $(System.ArtifactsDirectory)/**/*.zip
